spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    password: 123456
        password: 123
        url: jdbc:mysql://10.100.104.36:3306/device?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
#    url: jdbc:mysql://localhost:3306/device?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8

# 指定文件上传路径
fileupload:
  uploadPath: D:\\upload
#  uploadPath: /home/monkey/upload
#  uploadPath: /root/upload


